### ISSUE TITLE
Apple Notification Failed for some unknown reason

### ISSUE THREAD

**Issue by danut-betuel** [nvlad/pushsharp.apple.http2#3]
Sometimes I get this error and push notifications doesn't come anymore:

Apple Notification Failed for some unknown reason : System.TimeoutException: The operation has timed out.
at HttpTwo.Http2Client.<Send>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at HttpTwo.Http2Client.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at HttpTwo.Http2Client.<Post>d__15.MoveNext()

Does anyone know what should I do ?

**Comment by norcis** [comment]
Same for me. Have you found a solution, @danut-betuel ?
